---
title: "Climate Change"
author: "Kristin Gill and Genevieve Chiong"
date: "4/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(stringr)
```

Historical Data
```{r}
historical <- read_csv(here("data", "2948034.csv")) %>% 
  clean_names() %>% 
  mutate(tavg = (tmax+tmin)/2) %>% 
  select(date, tavg) %>% 
  mutate(date = as_date(date)) %>% 
  mutate(year = year(date)) %>% 
  mutate(month = month(date)) %>% 
  filter(month == 7)

historical_average <- historical %>% 
  group_by(year, month) %>% 
  summarize(month_average = mean(tavg)) %>% 
  mutate(temperature_c = (month_average - 32)/1.8)

historical_merge <- merge(historical_average, historical)
```

Projection Data
```{r}
noaa_119 <- read_csv(here("data", "noaa_119.csv")) %>% 
  mutate(time = as_datetime(time)) %>% 
  mutate(date = date(time)) %>% 
  mutate(time = as.character(time)) %>% 
  separate(col = time, into = c("date_na", "time"), sep = " ") %>%
  mutate(temperature_c_noaa = tas - 273.15) %>% 
  select(date, time, temperature_c_noaa) %>% 
  filter(time == "12:00:00") # noon time temperatures

noaa_585 <- read_csv(here("data", "noaa_585.csv")) %>% 
  mutate(time = as_datetime(time)) %>% 
  mutate(date = date(time)) %>% 
  mutate(time = as.character(time)) %>% 
  separate(col = time, into = c("date_na", "time"), sep = " ") %>%
  mutate(temperature_c_noaa = tas - 273.15) %>% 
  select(date, time, temperature_c_noaa) %>% 
  filter(time == "12:00:00") # noon time temperatures

miroc_119 <- read_csv(here("data", "miroc_119.csv")) %>% 
  mutate(time = as_datetime(time)) %>% 
  mutate(date = date(time)) %>% 
  mutate(time = as.character(time)) %>% 
  separate(col = time, into = c("date_na", "time"), sep = " ") %>%
  mutate(temperature_c_miroc = tas - 273.15) %>% 
  select(date, time, temperature_c_miroc) %>% 
  filter(time == "12:00:00") # noon time temperatures

miroc_585 <- read_csv(here("data", "miroc_585.csv")) %>% 
  mutate(time = as_datetime(time)) %>% 
  mutate(date = date(time)) %>% 
  mutate(time = as.character(time)) %>% 
  separate(col = time, into = c("date_na", "time"), sep = " ") %>%
  mutate(temperature_c_miroc = tas - 273.15) %>% 
  select(date, time, temperature_c_miroc) %>% 
  filter(time == "12:00:00") # noon time temperatures
```

Just June
```{r}
miroc_119_june <- miroc_119 %>% 
  mutate(month = month(date)) %>% 
  filter(month == 07)

miroc_585_june <- miroc_585 %>% 
  mutate(month = month(date)) %>% 
  filter(month == 07)

noaa_119_june <-noaa_119 %>% 
  mutate(month = month(date)) %>% 
  filter(month == 07)

noaa_585_june <- noaa_585 %>% 
  mutate(month = month(date)) %>% 
  filter(month == 07)

ssp_119 <- merge(noaa_119_june, miroc_119_june, by = "date")

ssp_585 <- merge(noaa_585_june, miroc_585_june, by = "date")
```

SSP 119
```{r}
ggplot() +
  geom_line(data = noaa_119_june, aes(x = date,
                            y = temperature_c_noaa,
                            color = "blue"),
            size = 0.6) +
  geom_line(data = miroc_119_june, aes(x = date,
                                  y = temperature_c_miroc,
                                  color = "darkgreen"),
            size = 0.6) +
  geom_smooth(data = noaa_119_june, aes(x = date,
                                        y = temperature_c_noaa),
            color = "blue3",
            size = 0.6) +
  geom_smooth(data = miroc_119_june, aes(x = date,
                                        y = temperature_c_miroc),
            color = "darkgreen",
            size = 0.6) +
  theme_minimal() +
  scale_colour_manual(labels = c("NOAA", "MIROC", "trend", "trend"),
                     values = c("blue", "darkgreen", "blue", "darkgreen")) +
  labs(x = "Date",
       y = "Temperature (Celsius)",
       color = "Model",
       title = "SSP 1-1.9 Temperature Projections",
       subtitle = "San Diego County, CA (2015-2100)")
```

SSP 119
```{r}
ggplot(data = ssp_119, aes(x = temperature_c_noaa,
                           y = temperature_c_miroc)) +
  theme_minimal() +
  geom_point() +
  labs(x = "NOAA Temperature Projections (Celsius)",
       y = "MIROC Temperature Projections (Celsius)",
       title = "NOAA vs. MIROC SSP 1-1.9 Temperature Projection Comparison",
       subtitle = "San Diego County, CA (2015-2100)") +
  geom_smooth(data = ssp_119, aes(x = temperature_c_noaa,
                                  y = temperature_c_miroc),
              method = lm) +
  ggpubr::stat_regline_equation(label.x = 24, label.y = 28)
```

SSP 585
```{r}
ggplot() +
  geom_line(data = noaa_585_june, aes(x = date,
                            y = temperature_c_noaa,
                            colour = "purple"),
            size = 0.6) +
  geom_line(data = miroc_585_june, aes(x = date,
                                  y = temperature_c_miroc,
                                  colour = "red"),
            size = 0.6) +
  theme_minimal() +
  scale_colour_manual(labels = c("NOAA", "MIROC"),
                     values = c("purple", "red")) +
  labs(x = "Date",
       y = "Temperature (Celsius)",
       color = "Model",
       title = "SSP 5-8.5 Temperature Projections",
       subtitle = "San Diego County, CA (2015-2100)")
```

SSP 585
```{r}
ggplot(data = ssp_585, aes(x = temperature_c_noaa,
                           y = temperature_c_miroc)) +
  theme_minimal() +
  geom_point() +
  labs(x = "NOAA Temperature Projections (Celsius)",
       y = "MIROC Temperature Projections (Celsius)",
       title = "NOAA vs. MIROC SSP 5-8.5 Temperature Projection Comparison",
       subtitle = "San Diego County, CA (2015-2100)") +
  geom_smooth(data = ssp_585, aes(x = temperature_c_noaa,
                                  y = temperature_c_miroc),
              method = lm) +
  ggpubr::stat_regline_equation(label.x = 24, label.y = 28)
```


```{r}
ggplot() +
  geom_line(data = noaa_119_june, aes(x = date,
                            y = temperature_c_noaa,
                            colour = "blue")) +
  geom_line(data = miroc_119_june, aes(x = date,
                            y = temperature_c_miroc,
                            colour = "darkgreen")) +
  geom_line(data = noaa_585_june, aes(x = date,
                            y = temperature_c_noaa,
                            colour = "purple")) +
  geom_line(data = miroc_585_june, aes(x = date,
                            y = temperature_c_miroc,
                            colour = "red")) +
  geom_line(data = historical_merge, aes(x = date,
                            y = temperature_c,
                            colour = "black")) +
  labs(x = "Date",
       y = "Temperature (Celsius)",
       color = "Model",
       title = "Historical and Projected Temperature Trends",
       subtitle = "San Diego, CA") +
  scale_colour_manual(labels = c("Historical", "NOAA SSP 1-1.9", "MIROC SSP 1-1.9", "NOAA SSP 5-8.5", "MIROC SSP 5-8.5"),
                     values = c("black", "darkgreen", "blue", "red", "purple")) +
  theme_minimal()
```

